processors:
  batch:
  filter/drop_servicebus_receive_spans:
    error_mode: ignore
    traces:
      span:
        # drop the receive spans that provide no value
        - 'attributes["messaging.operation"] == "receive" and name == "ServiceBusReceiver.Receive"'
        - 'attributes["messaging.operation"] == "settle" and name == "ServiceBusReceiver.Complete"'
        - 'attributes["messaging.operation"] == "publish" and name == "ServiceBusReceiver.Send"'
  
service:
  pipelines:
    traces:
      processors: 
        - batch
        - filter/drop_servicebus_receive_spans
