name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./Config/Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: mssql  
      MSSQL_SA_PASSWORD: "1tslocal!dontcare"
      ACCEPT_EULA: "Y"
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  mssql:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      sb-emulator:
        aliases:
          - "mssql"
    environment:
      MSSQL_SA_PASSWORD: "1tslocal!dontcare"
      ACCEPT_EULA: "Y"
networks:
  sb-emulator: